### PR TITLE
Pass test name to failure callback

### PR DESCRIPTION
**Pull request by julien-meichelbeck**

### CODE REVIEW

**Comment by y-yagi** [comment]
Looks good. Thanks!

**Comment by y-yagi** [comment]
Sorry after merging, please let me ask a question. 
Is it only the test name you need? Is the test class name unnecessary?

**Comment by julien-meichelbeck** [comment]
Hey, yeah it would be good to also add the class name.

(By the way, the readme is messed up, my bad!)

**Comment by y-yagi** [comment]
Thanks for your answer! I see. I will add class name later.
(Hahah, no problem :wink: )

**Pull request merged**
